Redesign clock port
ARMmbed/mbed-aws-client pull request #15
Opened 2020-08-13 07:28 UTC by boraozgen

@LDong-Arm opened again since the previous one had another commit in it.

Refers to #12.

Uses the shared event queue instead of threads.

2020-08-14 15:57 UTC, LDong-Arm requested changes
@boraozgen Thanks a lot for your contribution, it looks to me to be the right approach. Event (or EventQueue) is the way to do non-IRQ timers. I just made small suggestions to timer destroy.

2020-08-14 15:57 UTC, LDong-Arm commented on mbed/src/iot_clock.cpp
> +    auto timer = *pTimer;
```suggestion
    auto timer = *pTimer;
    
    if (pTimer == NULL) {
        return;
    }
```

2020-08-14 15:57 UTC, LDong-Arm commented on mbed/src/iot_clock.cpp
> +    delete timer;
```suggestion
    delete timer;
    *pTimer = NULL;
```

2020-08-14 16:05 UTC, LDong-Arm commented
@ARMmbed/mbed-os-core Any thoughts?

2020-09-03 09:28 UTC, LDong-Arm approved these changes
LGTM. Can we get it in? @evedon

2020-09-03 11:53 UTC, evedon approved these changes

2020-09-03 11:55 UTC, merged

2020-10-19 16:41 UTC, adbridge commented
This should have gone to the development branch not master ...

2020-10-19 16:45 UTC, LDong-Arm commented
@adbridge This is a library, not an example. As with any non-examples, there's no development branch.
The example is https://github.com/ARMmbed/mbed-os-example-for-aws which controls the version of this library.

2020-10-20 10:05 UTC, adbridge commented
@LDong-Arm libraries should still be under control and have release versions and thus have a development process. I discussed this with @evedon yesterday. This needs to be investigated further.

2020-10-21 09:09 UTC, evedon commented
As this is a library and not an example, I'd rather that we follow a simple development process and go directly to master as we do in mbed-os.